# -*- coding: utf-8 -*-
"""Sudoku Generator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nTOliKwYzslDisAJKTuzE5q1KQCnASb6

# Sudoku Generator

Importing Libraries
"""

import random
import copy

"""Print Board"""

def print_board(board):
    for r in range(9):

        if r % 3 == 0 and r != 0:
            print("-" * 21)

        for c in range(9):

            if c % 3 == 0 and c != 0:
                print("|", end=" ")

            print(board[r][c], end=" ")

        print()

"""Find Empty Cell"""

def find_empty(board):

    for r in range(9):
        for c in range(9):

            if board[r][c] == 0:
                return r, c

    return None

"""Check if Number is Valid"""

def is_valid(board, row, col, num):

    # Check row
    for c in range(9):
        if board[row][c] == num:
            return False

    # Check column
    for r in range(9):
        if board[r][col] == num:
            return False

    # Check 3x3 box
    start_row = (row // 3) * 3
    start_col = (col // 3) * 3

    for r in range(start_row, start_row + 3):
        for c in range(start_col, start_col + 3):

            if board[r][c] == num:
                return False

    return True

"""Fill Board Randomly
# (Modified Sudoku Solver)
"""

def fill_board(board):

    empty = find_empty(board)

    if empty is None:
        return True

    row, col = empty

    numbers = list(range(1, 10))
    random.shuffle(numbers)

    for num in numbers:

        if is_valid(board, row, col, num):

            board[row][col] = num

            if fill_board(board):
                return True

            board[row][col] = 0

    return False

"""Count Number of Solution"""

def count_solutions(board):

    empty = find_empty(board)

    if empty is None:
        return 1

    row, col = empty

    total = 0

    for num in range(1, 10):

        if is_valid(board, row, col, num):

            board[row][col] = num

            total += count_solutions(board)

            board[row][col] = 0

    return total

"""Remove Numbers"""

def remove_numbers(board, difficulty):

    levels = {
        "easy": 35,
        "medium": 45,
        "hard": 53
    }

    remove_count = levels[difficulty]

    removed = 0

    while removed < remove_count:

        row = random.randint(0, 8)
        col = random.randint(0, 8)

        if board[row][col] == 0:
            continue

        backup = board[row][col]
        board[row][col] = 0

        test_board = copy.deepcopy(board)

        # Keep removal only if puzzle still has ONE solution
        if count_solutions(test_board) != 1:
            board[row][col] = backup
        else:
            removed += 1

"""Generate Sudoku"""

def generate_sudoku(level="easy"):

    board = [[0 for _ in range(9)] for _ in range(9)]

    fill_board(board)

    solution = copy.deepcopy(board)

    remove_numbers(board, level)

    return board, solution

"""Generator"""

difficulty = input("Choose difficulty (easy / medium / hard): ").lower()

puzzle, solution = generate_sudoku(difficulty)

print("\nGenerated Puzzle:\n")
print_board(puzzle)

print("\nSolution:\n")
print_board(solution)

